<?php

class ImageController extends BasicController {
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Helper::import('image');
    }

    public function addContentImageAction() {
        $ret = qiniu_image_upload('file');
        $res = new stdClass();
        $res->link = $ret;
        echo $ret ? stripcslashes(json_encode($res)) : null;
    }
}